name: .NET WinForms Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true -o publish

    - name: Zip published app
      run: Compress-Archive -Path publish\\* -DestinationPath embold-ssh-win-x64.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: embold-ssh-win-x64
        path: embold-ssh-win-x64.zip