name: .NET WinForms Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -r win-x64 --self-contained true -o publish

    - name: Zip published app
      run: Compress-Archive -Path publish\\* -DestinationPath embold-ssh-win-x64.zip

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: embold-ssh-win-x64
        path: embold-ssh-win-x64.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "emBold SSH Handler ${{ github.ref_name }}"
        body: |
          Windows SSH protocol handler for easy ssh:// link integration.
          - User-friendly terminal and icon selection
          - Clean install/uninstall (removes registry entries)
          - No PowerShell/VBS scripts; all logic in C#
          - Defender-friendly, self-contained .NET 8 WinForms app
          - See README for usage and installation instructions
        files: embold-ssh-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}